Controllers/CinemasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using OnlineShop.Data;
using OnlineShop.Data.Base;
using OnlineShop.Models;
using OnlineShop.Models.Combined;

namespace OnlineShop.Controllers
{
    public class CinemasController : Controller
    {
        private readonly IGenericRepository<Cinema> _service;

        public CinemasController(IGenericRepository<Cinema> service)
        {

            _service = service; 
        } 
        public async Task<IActionResult> Index()
        {
            Cinema cinema = new Cinema();
            IEnumerable<Cinema> cinemaList = await _service.GetAll();

            CinemaViewModel viewModel = new CinemaViewModel
            {
                Cinema = cinema,
                Cinemas = cinemaList
            };

            return View(viewModel);    
        }

        [Authorize]
        [HttpPost]
        public async Task<JsonResult> CreateWithModal(Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    status = "failure",
                    formErrors = ModelState.Select(kvp => new { key = kvp.Key, errors = kvp.Value?.Errors.Select(e => e.ErrorMessage) })
                });
            }

       
            await _service.Add(cinema);
            return Json("Product Details Saved");         

        }

        [Authorize]                                               
        public async Task<IActionResult> Edit(int id)
        {

            var cinemaDetails = await _service.GetById(id);
            if (cinemaDetails == null)
            {
                return Json( new
                {
                    status = "failure",
                    formErrors = ModelState.Select(kvp => new { key = kvp.Key, errors = kvp.Value?.Errors.Select(e => e.ErrorMessage) })
                });
            }

            return Json(cinemaDetails);     

        }

        [Authorize]
        [HttpPost]  
        public async Task<IActionResult> Update(Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    status = "failure",
                    formErrors = ModelState.Select(kvp => new { key = kvp.Key, errors = kvp.Value?.Errors.Select(e => e.ErrorMessage) })    
                });
            }

            await _service.Update(cinema);
            return Json("Product Details Updated");
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var cinemaData = await _service.GetById(id);
            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    status = "failure",
                });
            }

            return Json(cinemaData); 

        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Cinema tempCinema)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { status = "failure" });
            }
            await _service.Delete(tempCinema);
            return Json("Product Details Deleted");


        }   
    }
}

Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using OnlineShop.Data;
using OnlineShop.Data.Base;
using OnlineShop.Data.Enum;
using OnlineShop.Models;
using System.Collections;
using System.Collections.Generic;
using System.Security.Claims;

namespace OnlineShop.Controllers
{
    public class MoviesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IdentityDbContext _identityDbContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public MoviesController(UserManager<ApplicationUser> userManager , AppDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

      

        public async Task<IActionResult> Index()
        {
            var allMovies = await _context.Movies.Include(n => n.Cinema).OrderBy(n => n.Name).ToListAsync();
          
            return View(allMovies);
        }


        public async Task<List<Producer>> GetAllProducers() => await _context.Producers.ToListAsync();
        public async Task<List<Cinema>> GetAllCinemas() => await _context.Cinemas.ToListAsync();
  
        public static IEnumerable<SelectListItem> GetEnumValues<TEnum>()
        {
            return Enum.GetValues(typeof(TEnum))
                       .Cast<TEnum>()
                       .Select(e => new SelectListItem
                       {
                           Value = e.ToString(),
                           Text = e.ToString()
                       })
                       .ToList();
        }
           
        public async Task<IActionResult> Create()
        {

            List<Cinema> cinemas = await GetAllCinemas();
            List<Producer> producers = await GetAllProducers();
            List<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem> MovieCategoryList;


            Dictionary<int, string> cinemDropdownValues = new Dictionary<int, string>();
            Dictionary<int, string> prodDropdownValues = new Dictionary<int, string>();

            foreach (var cinema in cinemas)
            {
                cinemDropdownValues.Add(cinema.Id, cinema.Name);
            }

            foreach (var prod in producers)
            {
                prodDropdownValues.Add(prod.Id, prod.FullName);
            }


            ViewBag.DropDownValues = prodDropdownValues;
            ViewBag.CinemaDropDownValues = cinemDropdownValues;

            
            ViewBag.EnumSelectList = GetEnumValues<MovieCategory>();

            return View();

        }

        [HttpPost]
        public IActionResult Create(Movie model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);

            }
            
            _context.Movies.Add(model); 
            _context.SaveChanges(); 
            return RedirectToAction("Index");   
        }

        public async Task<IActionResult> SearchMovies(string movie)
        {
            if(!String.IsNullOrEmpty(movie)) 
            {
                var moviesResult = await _context.Movies.Where(x => x.Name.Contains(movie)).ToListAsync();

                if (moviesResult.Count > 0)
                {
                    return View(moviesResult);
                }
               
              
            }
            return RedirectToAction("Index");
        }


        [Authorize]
        public  IActionResult PressCart()
        {
            List<Movie> movies = new List<Movie>();

            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var items = _context.ShoppingCarts.Where(x => x.UserId == userid);

            var moviesId = new List<int>(); 

            foreach(ShoppingCart item in items)
            {
                moviesId.Add(item.MovieId);
            }

            movies = _context.Movies.Where(b => moviesId.Contains(b.Id)).ToList();

            foreach(Movie item in movies)
            {
                System.Diagnostics.Debug.WriteLine("********&&&&&&*********");

                System.Diagnostics.Debug.WriteLine(item.Name+"|"+item.Id +"|"+item.Price);
                System.Diagnostics.Debug.WriteLine(userid);
                System.Diagnostics.Debug.WriteLine("********&&&&&&*********");
            }

            return View(movies);
        }


        [Authorize]
        [HttpPost]
        public  IActionResult DeleteItemInCard(int id)
        {

            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var item =  _context.ShoppingCarts.FirstOrDefault(x => x.Id == id && x.UserId ==userid );
            if(item is not null)
            {
                try
                {
                    _context.ShoppingCarts.Remove(item);
                    _context.SaveChanges();     
                }
                catch 
                {
                    return View("NotFound");
                }
            }
          
            return View("Index"); 
        }



        
        [Authorize]
        [HttpPost]
        public IActionResult AddItemToCart(int movieId)
        {
           
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);

            System.Diagnostics.Debug.WriteLine("********&&&&&&*********");
            System.Diagnostics.Debug.WriteLine(movieId.ToString());
            System.Diagnostics.Debug.WriteLine(userid);
            System.Diagnostics.Debug.WriteLine("********&&&&&&*********");


            if (userid != null && movieId > 0)
            {
                _context.ShoppingCarts.Add(new ShoppingCart { UserId = userid, MovieId = movieId });
                _context.SaveChanges();
                TempData["AlertMessage"] = "Movie Added Successfuly";
                return RedirectToAction("Index");
            }

            return View("Index");

        }

        [HttpGet]
        public async Task<IActionResult> OrderByDate()
        {
            var movies = await _context.Movies.Include(n => n.Cinema).OrderBy(n => n.StartDate).ToArrayAsync();

            return View(movies);    
        }


    }
}

Controllers/ProducersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;
using OnlineShop.Data.Base;
using OnlineShop.Models;

namespace OnlineShop.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IGenericRepository<Producer> _service;

        public ProducersController(IGenericRepository<Producer> service)
        {
            _service = service;
        }

        public async  Task<IActionResult> Index()
        {
            var allProducers = await _service.GetAll();
            return View(allProducers);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePicture,Bio")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            await _service.Add(producer);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _service.GetById(id);
            if (producerDetails == null)
            {
                return View("Empty");
            }

            return View(producerDetails);
        }

        public async Task<IActionResult> Edit(int id)
        {

            var producerDetails = await _service.GetById(id);
            if (producerDetails == null)
            {
                return View("NotFound");
            }
            return View(producerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }

            await _service.Update(producer);
            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Delete(int id)
        {
            var producerData = await _service.GetById(id);
            if (producerData == null)
            {
                return View("NotFount");
            }
            return View(producerData);

        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var tempProducer = await _service.GetById(id);
            if (tempProducer == null)
            {
                return View("NotFound");
            }
            await _service.Delete(tempProducer);
            return RedirectToAction(nameof(Index));


        }
    }
}

Views/Shared/NotFound.cshtml
<div class=" row text-center">
   <div class ="col-md-6 offset-3">
        <h1 class="text-info"> You've reached the end of the internet</h1>
        </hr>
        <a class="btn btn-outline-secondary" asp-controller = "Actors" asp-action="Index">Home Page</a>
   </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"/>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.min.js"></script>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">OnlineShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                           <a class=" nav-link text-dark" asp-controller="Movies" asp-action="Index"><i class="bi bi-film"></i>Movies</a>
                        </li>
                        <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
                          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           <i class="bi bi-gear"></i>Management
                           </a>
                                
                            
                           <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                               <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index" ><i class="bi bi-camera-reels">
                               </i>Cinemas </a>                             
                               <a class="dropdown-item" asp-controller="Producers" asp-action="Index" ><i class="bi bi-headset">
                               </i>Producers </a> 
                               <a class="dropdown-item" asp-controller="Actors" asp-action="Index" ><i class="bi bi-person-square">
                               </i>Actors </a>
                           </div>                                                
                        </li>

                        <li class=" nav-item">
                        
                            <a class="nav-link text-dark" asp-controller = "Account" asp-action = "Index"><i class = "fas fa-sign-in-alt"></i>LogIn</a>
                    
                        </li>
                    </ul>    
                        <form method="post" asp-action="PressCart">
                            <button type="submit">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                </svg>
                            </button>
                        </form>

                        
              

                    <form class="my-lg-2" asp-controller="Movies" asp-action ="SearchMovies" style="padding-right: 25px;">
                        <div class=" input-group">
                            <input name = "movie" type="text" class="form-control " placeholder="Search for a movie...">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class=" bi bi-search"></i></button>

                        </div>
                    </form>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>